title: Brandon Williams
logo: mypic.png
description: >
  Research Associate with 3+ years of experience in the asset management industry and a master's degree in Business Analytics from College of William and Mary. 
  I hold a BS in Mathematics and Economics. Previously, worked as a student researcher for the Summer Science Institute at the University of Mary Washington.
  View my LinkedIn Profile: https://www.linkedin.com/in/brandonwilliamsm/
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
colors:
  crimson: '#900C3F'
